import { type Metadata } from 'next'
import { Inter } from 'next/font/google'

import './globals.css'
import '@trroev/ui/styles'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
}

const RootLayout = ({
  children,
}: {
  children: React.ReactNode
}): JSX.Element => {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}

export default RootLayout
