import { type Metadata } from 'next'

import './globals.css'
import '@trroev/ui/styles'

import { RootLayout } from '@trroev/layout/RootLayout'

const metadata: Metadata = {
  title: 'Turbo trroev',
  description: 'Generated by create turbo',
}

export default RootLayout
export { metadata }
